id: P009140
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1232
  title: དྲི་མེད་ཆོ་ག
  author: ''
  volumes:
    7b59670f66b64a0ba4e6f0ca00b57822:
      image_group_id: I1CZ1705
      title: ''
      volume_number: 1
      total_pages: 96
      base_file: v001.txt
